### ISSUE TITLE
[UNDER-DISCUSSION] Surrogate-based sensitivity analysis when you have dependent variables

### ISSUE THREAD

**Issue by Jimmy-INL** [idaholab/raven#1321]
--------
--------

**Summary of the topic to be discussed with the development team**
In the training of ROMs, we should not include dependent variables among the inputs, but what if we need to perform a sensitivity analysis on these? Some ROMs already allow the inclusion of dependent/correlated inputs in the training process, and although there are some warnings about high colinearity/condition number, warnings are not that. impactful as users tend to ignore them. We should find some way to save the user from that mistake at the ROM level.

**Describe the solution you'd like to be implemented**
1. Include the correlation function in the serialization and perform an additional sampling-based sensitivity analysis on this function.
2. Maybe add the correlation function as an external model and build an ensemble model out of that.
3. Please edit/add other suggestions if you wish. 

**Describe alternatives you've considered**

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with the under_discussion type?
- [ ] 2. If implemented, it will add a new requirement?
- [ ] 3. Is a rationale provided? (Such as explaining why the improvement is needed )

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. The discussion determined the addition of a new ```task``` issue?

**Comment by PaulTalbot-INL** [comment]
My thoughts:
- Add meta data to a Realization that includes where each variable value came from (what Sampler, what Function, or what Model)
- When we train a ROM, we check the meta for the Realization for what source the input variables came from, and if it's a dependent variable, we keep it out of the training space and sideline it into an "auxiliary output" space (internally, the user doesn't really need to know)
- For `dependent` inputs (those generated via the "comma" method or a Function), when we go to serialize the ROM:
  - If the source object (e.g. Function) is still in memory, maybe we can serialize it to go along with the ROM; this might require adding the Function as well in the next RAVEN input that will use the serialized ROM
  - If not, we Warning or possibly Error indicating that the variable won't be able to be serialized because critical information is missing; I don't know what we do for the user in this case
