### ISSUE TITLE
[DEFECT] Executing OMP software is not functional

### ISSUE THREAD

**Issue by aalfonsi** [idaholab/raven#1632]
--------
Defect Description
--------

**Describe the defect**

##### What did you expect to see happen?

We tried to run a job using an OMP software (serpent) (using 28 threads/job). 
The node we are running on has 256 processors (shared memory). 
I expected all the processors in the node to be used to execute 9 parallel tasks.
The RunInfo we used is as follows:

```
  <RunInfo>
    ...
    <batchSize>9</batchSize>
    <mode>mpi</mode>
    <NumThreads>28</NumThreads>
    <threadParameter>-omp %NUM_CPUS%</threadParameter>
    ...
  </RunInfo>
```

##### What did you see instead?

The code does not seem to run exploiting the OMP processors. In the following picture, it can be seen that
most of the processors are not running. 

<img width="1434" alt="Screen Shot 2021-08-05 at 4 13 23 PM (1)" src="https://user-images.githubusercontent.com/26668536/128537881-d0970a4e-9537-4bef-bfba-e24c344062c4.png">

##### Do you have a suggested fix for the development team?

N/A

**Describe how to Reproduce**
1. Use an OMP software (e.g. MOOSE)
2. Execute a Monte Carlo using multiple threads
3. 
4. 

**Screenshots and Input Files**
N/A

**Platform (please complete the following information):**
 - OS: Linux (Centos) cluster
 - Version: N/A
 - Dependencies Installation: CONDA

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [ ] 1. If the issue is a defect, is the defect fixed?
- [ ] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by aalfonsi** [comment]
@drewj-usnctech

**Comment by joshua-cogliati-inl** [comment]
Hm, dumb question, but if you run the serpent input file manually, do you get better processor utilization? (and if so, what qsub* command did RAVEN generate versus what did you manually use?)

*I am assuming qsub, but if some other system is used, answer for that instead.

**Comment by joshua-cogliati-inl** [comment]
Oh, and for the image, is one Serpent instance running on mostly on 2 processors, or is that 2 Serpent instances or 1 Serpent 1 python ...?

**Comment by aalfonsi** [comment]
Hi Josh, sorry for the delay.

Yes. When we run serpent manually we get perfect utilization (even if we run manually multiple instances in the same node)

The command raven creates for this input file is: ```sss2 -noplot my_input.i -omp 28```

**Comment by aalfonsi** [comment]
That image shows the cpus usage in the node. All of them should be at >>0% utilization. That picture is for 9 serpent runs (concurrent) using 28 threads each.

**Comment by aalfonsi** [comment]
@joshua-cogliati-inl

**Comment by joshua-cogliati-inl** [comment]
Strange. I still am interesting in the precommand, the postcommand, and then final command used for Serpent.

**Comment by joshua-cogliati-inl** [comment]
If I had to guess either the command is getting messed up, or some environmental variable is getting messed up. (Which I admit is pretty vague.)  It might be worth your time to compare the output of ```env``` from inside RAVEN versus manually run (don't post the full output here, there is probably private info in it.).

**Comment by joshua-cogliati-inl** [comment]
The variables starting with OMP, especially ```OMP_NUM_THREADS``` might be worth looking at.

**Comment by drewj-usnctech** [comment]
@joshua-cogliati-inl thank you for picking this up and providing some feedback. I can hopefully provide some more insight after some testing on our cluster.

In all cases, the `OMP_NUM_THREADS` environment variable was `unset` before running raven.

## What worked
 Creating a "fake" serpent executable in the working directory and path such that `sss2` **always** ran with some number of threads, e.g.,
```bash
$ cat sss2
#!/usr/bin/env bash
/path/to/actual/sss2 -omp N @$
```
and running without `<mode>mpi</mode>`.

I found this worked better than `alias sss2="/path/to/actual/sss2 -omp N $@"` probably due to how RAVEN and python pass environment variables to subprocesses. I don't think aliases are transferred. 

I found that the "full" Serpent command (as far as RAVEN was concerned) was just `sss2 -noplot [input]` and no thread parameters were passed. The real Serpent command (after going through my psuedo-alias) was `sss2 -omp N -noplot [input]`.

## What didn't work
- Running normal Serpent in MPI mode
- Running the "aliased" Serpent in MPI mode
- Disabling setting of `MV2_ENABLE_AFFINITY` via
```diff
diff --git a/framework/CustomModes/MPILegacySimulationMode.py b/framework/CustomModes/MPILegacySimulationMode.py
index c10d14a1d..a015312f9 100644
--- a/framework/CustomModes/MPILegacySimulationMode.py
+++ b/framework/CustomModes/MPILegacySimulationMode.py
@@ -194,7 +194,7 @@ class MPILegacySimulationMode(Simulation.SimulationMode):
 
     #Disable MPI processor affinity, which causes multiple processes
     # to be forced to the same thread.
-    os.environ["MV2_ENABLE_AFFINITY"] = "0"
+    # os.environ["MV2_ENABLE_AFFINITY"] = "0"
 
     # Create the mpiexec pre command
     # Note, with defaults the precommand is "mpiexec -f nodeFile -n numMPI"
diff --git a/framework/CustomModes/MPISimulationMode.py b/framework/CustomModes/MPISimulationMode.py
index 7457f5eec..390499980 100644
--- a/framework/CustomModes/MPISimulationMode.py
+++ b/framework/CustomModes/MPISimulationMode.py
@@ -103,7 +103,7 @@ class MPISimulationMode(Simulation.SimulationMode):
 
     #Disable MPI processor affinity, which causes multiple processes
     # to be forced to the same thread.
-    os.environ["MV2_ENABLE_AFFINITY"] = "0"
+    # os.environ["MV2_ENABLE_AFFINITY"] = "0"
 
     # Create the mpiexec pre command
     # Note, with defaults the precommand is "mpiexec -f nodeFile -n numMPI"
diff --git a/framework/Driver.py b/framework/Driver.py
index 1281088c6..62b816aba 100755
--- a/framework/Driver.py
+++ b/framework/Driver.py
@@ -46,7 +46,7 @@ except (AttributeError,ImportError):
   builtins.profile = lambda f: f
 
 #warning: this needs to be before importing h5py
-os.environ["MV2_ENABLE_AFFINITY"]="0"
+# os.environ["MV2_ENABLE_AFFINITY"]="0"
 
 frameworkDir = os.path.dirname(os.path.abspath(__file__))
```

## Other information

I'm not sure what environment variables you'd be intererested in, but I have the `env` command in my slurm submission script. Some things that I think might be useful
```shell
$ grep "^SLURM.*NODE" slurm.out 
SLURM_NODEID=0
SLURMD_NODENAME=c1
SLURM_TASKS_PER_NODE=256
SLURM_NNODES=1
SLURM_JOB_NODELIST=c1
SLURM_NODELIST=c1
SLURM_JOB_CPUS_PER_NODE=256
SLURM_NODE_ALIASES=(null)
SLURM_CPUS_ON_NODE=256
SLURM_JOB_NUM_NODES=1
```

@aalfonsi and I are still investigating on our end if we need to compile Serpent in such a way that it communicates better with RAVEN and MPI. I've tried the MPI-enabled compilation and found that it did not help nor hinder our efforts; it performed as well or poorly as the OMP-only version.

## Possible fix

Since it appears that passing `-omp N` to Serpent works when running without MPI (e.g., `sss2 -omp N -noplot [input]` vs. `mpiexec -n 1 sss2 -omp N -noplot [input]`), adding the `-omp N` post-command _should_ be sufficient. Here, we have a parallel application that does not have MPI capability (not that Serpent can't, we just tend to run with OMP only) and thus could take advantage of the threading parameters.

If a user provides both `<NumThreads>N</NumThreads>` and `<threadParameter>-omp %NUM_CPUS%</threadParameter>`, would that be sufficient information to add the post-command, even if we are not running in MPI mode?

**Comment by joshua-cogliati-inl** [comment]
Hm, threadParameter only seems to be used in MPI mode (and MPI legacy mode).  If omp is not working with mpiexec then that could be a problem.   

Fixing threadParameter to work without MPI is probably needed. Either SimulationMode in Simulation.py needs to modify the postcommand or evaluateSample in Models/Code.py needs to read the threadParameter.

**Comment by joshua-cogliati-inl** [comment]
Here is a suggested fix for non-mpi modes:
```diff
diff --git a/framework/Simulation.py b/framework/Simulation.py
index 48b0f9652..b5a2e1853 100644
--- a/framework/Simulation.py
+++ b/framework/Simulation.py
@@ -86,13 +86,19 @@ class SimulationMode(MessageUser):
       @ In, runInfoDict, dict, the run info
       @ Out, dictionary to use for modifications.  If empty, no changes
     """
+    newRunInfo = {}
     import multiprocessing
     try:
       if multiprocessing.cpu_count() < runInfoDict['batchSize']:
         self.raiseAWarning("cpu_count",multiprocessing.cpu_count(),"< batchSize",runInfoDict['batchSize'])
     except NotImplementedError:
       pass
-    return {}
+    if runInfoDict['NumThreads'] > 1:
+      newRunInfo['threadParameter'] = runInfoDict['threadParameter']
+      #add number of threads to the post command.
+      newRunInfo['postcommand'] =" {} {}".format(newRunInfo['threadParameter'],runInfoDict['postcommand'])
+
+    return newRunInfo
 
   def XMLread(self,xmlNode):
     """
```

**Comment by aalfonsi** [comment]
@joshua-cogliati-inl I added your suggestion in https://github.com/idaholab/raven/pull/1655.

(please take a look)
