### ISSUE TITLE
Update NOTICE.txt for Author list

### ISSUE THREAD

**Issue by alfoa** [idaholab/raven#17]
Update the NOTICE.txt file to add all the main contributors of the RAVEN project

**Comment by joshua-cogliati-inl** [comment]
Issue Review Checklist
- [x] 1. Is it tagged with a type: defect or improvement? *improvement*
- [x] 2. Is it tagged with a priority: critical, normal or minor? *normal*
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? *no impact to requiremnts*
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. *not defect*
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)1 *Yes*

Issue reviewed by @joshua-cogliati-inl

**Comment by joshua-cogliati-inl** [comment]
Issue Closure Checklist
- [x] 1. If the issue is a defect, is the defect fixed?  *Improvement made*
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.) *Not defect, nor is author list easily testable in the regression system*
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)? *No impact*
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)? *not defect*
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided? *Will be closed with merge request*

Issue close reviewed by @joshua-cogliati-inl
