### ISSUE TITLE
Documentation for Optimizer

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#46]
There are a couple things.

First, the gain parameters all have virtually identical documentation, which makes them difficult to differentiate, especially when one does not have access to the reference paper cited.

Second, there is a hard-coded input space for the SolutionExport of an Optimizer-based step, using the input "trajID", but this isn't mentioned in the user manual.  I couldn't find an example in the user guide either.  Some explanation of the necessary mechanics would be quite helpful.

Third, the node `<parameter>` is incorrectly listed as <Parameter> in the documentation (the example is correct).

Fourth, in the `<Functions>` block description, it indicates absence of Functions and the `<upperBound>` nodes results in an unconstrained problem; however, the `<upperBound>` nodes are indicated as required for each variable.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or improvement? ***improvement***
- [x] 2. Is it tagged with a priority: critical, normal or minor? ***normal***
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? ***n/a***
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. ***not a defect***
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.) ***yes***

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

**Comment by alfoa** [comment]
-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed? ***improvement***
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)  ***improvement***
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?  ***improvement***
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)?  ***improvement***
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided? ***PR #236***
