### ISSUE TITLE
Cleaning up the Typical History postprocessor

### ISSUE THREAD

**Issue by PaulTalbot-INL** [idaholab/raven#5]
Originally it was believed there was a bug in the TypicalHistory postprocessor; however, it was discovered that its operation is merely obfuscated by some coding choices.

For example, there are literally 0 comments in the postprocessor (aside from function definitions), and variable names such as "tempData" and "tempInp" don't give any clarity to what actions are being performed.

It would be immeasurably helpful in the future to add comments and rename variables so that we can debug/make use of this postprocessor more in the future.

Similarly, the documentation for this postprocessor could benefit from some explanatory examples.

**Comment by joshua-cogliati-inl** [comment]
Issue Review Checklist
- [x] 1. Is it tagged with a type: defect or improvement? *Yes*
- [x] 2. Is it tagged with a priority: critical, normal or minor? *Yes*
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements? *Unlikely to impact requirements*
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. *Not a defect*
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.) *Yes*

Issue reviewed by @joshua-cogliati-inl

**Comment by joshua-cogliati-inl** [comment]
Issue Closure Checklist
- [x] 1. If the issue is a defect, is the defect fixed? *Improvement made*
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.) *Not defect*
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)? *No email needed*
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)? *not defect*
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided? *Will be closed with merge request*

Issue close reviewed.
